[2024-10-27T14:23:43.188+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:23:43.215+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:23:43.238+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:23:43.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:23:43.311+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:23:43.301+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:23:43.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:23:43.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.703 seconds
[2024-10-27T14:24:29.809+0000] {processor.py:186} INFO - Started process (PID=149) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:24:29.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:24:29.820+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:24:29.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:24:29.860+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:24:29.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:24:29.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:24:29.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.153 seconds
[2024-10-27T14:25:17.259+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:25:17.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:25:17.316+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:25:17.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:25:17.559+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:25:17.545+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:25:17.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:25:17.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.553 seconds
[2024-10-27T14:25:54.738+0000] {processor.py:186} INFO - Started process (PID=238) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:25:54.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:25:54.813+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:25:54.810+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:25:54.929+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:25:54.896+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:25:54.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:25:55.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.407 seconds
[2024-10-27T14:26:25.560+0000] {processor.py:186} INFO - Started process (PID=300) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:26:25.567+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:26:25.572+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:26:25.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:26:25.612+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:26:25.606+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:26:25.629+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:26:25.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.198 seconds
[2024-10-27T14:26:58.290+0000] {processor.py:186} INFO - Started process (PID=348) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:26:58.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:26:58.311+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:26:58.310+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:26:58.356+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:26:58.348+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:26:58.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:26:58.547+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.296 seconds
[2024-10-27T14:27:29.967+0000] {processor.py:186} INFO - Started process (PID=406) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:27:30.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:27:30.026+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:27:30.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:27:30.207+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:27:30.196+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:27:30.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:27:30.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.617 seconds
[2024-10-27T14:28:04.156+0000] {processor.py:186} INFO - Started process (PID=467) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:28:04.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:28:04.191+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:28:04.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:28:04.257+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:28:04.240+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:28:04.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:28:04.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.271 seconds
[2024-10-27T14:28:48.904+0000] {processor.py:186} INFO - Started process (PID=534) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:28:48.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:28:48.958+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:28:48.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:28:49.047+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:28:49.010+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:28:49.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:28:49.245+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.375 seconds
[2024-10-27T14:29:21.265+0000] {processor.py:186} INFO - Started process (PID=596) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:29:21.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:29:21.426+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:29:21.425+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:29:21.597+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:29:21.573+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:29:21.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:29:22.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 1.079 seconds
[2024-10-27T14:30:19.448+0000] {processor.py:186} INFO - Started process (PID=641) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:30:19.462+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:30:19.478+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:30:19.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:30:19.768+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:30:19.722+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:30:19.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:30:19.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.573 seconds
[2024-10-27T14:30:54.615+0000] {processor.py:186} INFO - Started process (PID=703) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:30:54.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:30:54.682+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:30:54.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:30:54.866+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:30:54.847+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:30:54.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:30:54.989+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.416 seconds
[2024-10-27T14:31:25.403+0000] {processor.py:186} INFO - Started process (PID=764) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:31:25.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:31:25.408+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:31:25.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:31:25.430+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:31:25.425+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:31:25.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:31:25.455+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.060 seconds
[2024-10-27T14:31:57.526+0000] {processor.py:186} INFO - Started process (PID=827) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:31:57.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:31:57.544+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:31:57.543+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:31:57.645+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:31:57.622+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:31:57.649+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:31:57.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.212 seconds
[2024-10-27T14:32:30.512+0000] {processor.py:186} INFO - Started process (PID=888) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:32:30.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:32:30.531+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:32:30.529+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:32:30.607+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:32:30.593+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:32:30.610+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:32:30.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.199 seconds
[2024-10-27T14:33:00.893+0000] {processor.py:186} INFO - Started process (PID=948) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:33:00.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:33:00.911+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:33:00.910+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:33:00.962+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:33:00.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:33:00.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:33:01.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.178 seconds
[2024-10-27T14:33:31.352+0000] {processor.py:186} INFO - Started process (PID=1012) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:33:31.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:33:31.358+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:33:31.357+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:33:31.406+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:33:31.400+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:33:31.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:33:31.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.099 seconds
[2024-10-27T14:34:01.681+0000] {processor.py:186} INFO - Started process (PID=1074) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:34:01.682+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:34:01.690+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:34:01.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:34:01.740+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:34:01.729+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:34:01.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:34:01.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.099 seconds
[2024-10-27T14:34:32.180+0000] {processor.py:186} INFO - Started process (PID=1137) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:34:32.183+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:34:32.188+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:34:32.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:34:32.215+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:34:32.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:34:32.217+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:34:32.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.095 seconds
[2024-10-27T14:35:07.476+0000] {processor.py:186} INFO - Started process (PID=1173) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:35:07.486+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:35:07.520+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:35:07.518+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:35:08.049+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:35:07.617+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:35:08.140+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:35:08.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 1.447 seconds
[2024-10-27T14:37:38.388+0000] {processor.py:186} INFO - Started process (PID=1236) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:37:38.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:37:38.410+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:37:38.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:37:38.508+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:37:38.483+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:37:38.518+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:37:38.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.555 seconds
[2024-10-27T14:38:39.078+0000] {processor.py:186} INFO - Started process (PID=1288) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:38:39.083+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:38:39.116+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:38:39.115+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:38:39.215+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:38:39.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:38:39.217+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:38:39.415+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.440 seconds
[2024-10-27T14:39:12.241+0000] {processor.py:186} INFO - Started process (PID=1332) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:39:12.266+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:39:12.323+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:39:12.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:39:12.455+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:39:12.432+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:39:12.463+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:39:12.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.717 seconds
[2024-10-27T14:39:49.187+0000] {processor.py:186} INFO - Started process (PID=1391) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:39:49.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:39:49.211+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:39:49.211+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:39:49.281+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:39:49.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:39:49.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:39:49.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.192 seconds
[2024-10-27T14:40:19.623+0000] {processor.py:186} INFO - Started process (PID=1454) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:40:19.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:40:19.635+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:40:19.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:40:19.694+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:40:19.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:40:19.698+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:40:19.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.142 seconds
[2024-10-27T14:47:38.388+0000] {processor.py:186} INFO - Started process (PID=104) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:47:38.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:47:38.425+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:47:38.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:47:38.509+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:47:38.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:47:38.521+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:47:38.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.289 seconds
[2024-10-27T14:49:00.096+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:49:00.102+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:49:00.131+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:49:00.130+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:49:00.205+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:49:00.190+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:49:00.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:49:00.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.374 seconds
[2024-10-27T14:49:34.244+0000] {processor.py:186} INFO - Started process (PID=219) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:49:34.298+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:49:34.426+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:49:34.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:49:34.783+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:49:34.722+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:49:34.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:49:35.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 1.524 seconds
[2024-10-27T14:50:21.873+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:50:21.914+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:50:22.005+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:50:21.986+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:50:22.402+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:50:22.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:50:22.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:50:22.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 1.036 seconds
[2024-10-27T14:51:03.710+0000] {processor.py:186} INFO - Started process (PID=301) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:51:03.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:51:03.753+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:51:03.750+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:51:04.065+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:51:03.973+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:51:04.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:51:04.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.975 seconds
[2024-10-27T14:51:52.096+0000] {processor.py:186} INFO - Started process (PID=357) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:51:52.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:51:52.142+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:51:52.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:51:52.230+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:51:52.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:51:52.233+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:51:52.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.634 seconds
[2024-10-27T14:52:27.535+0000] {processor.py:186} INFO - Started process (PID=411) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:52:27.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:52:27.555+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:52:27.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:52:27.599+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:52:27.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:52:27.602+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:52:27.691+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.202 seconds
[2024-10-27T14:53:06.380+0000] {processor.py:186} INFO - Started process (PID=469) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:53:06.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:53:06.418+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:53:06.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:53:06.516+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:53:06.505+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:53:06.527+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:53:06.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.373 seconds
[2024-10-27T14:53:40.788+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:53:40.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:53:40.821+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:53:40.820+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:53:40.893+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:53:40.880+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:53:40.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:53:41.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.285 seconds
[2024-10-27T14:55:35.497+0000] {processor.py:186} INFO - Started process (PID=592) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:55:35.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:55:35.780+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:55:35.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:55:35.815+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:55:35.806+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:55:35.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:55:35.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.570 seconds
[2024-10-27T14:56:13.594+0000] {processor.py:186} INFO - Started process (PID=637) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:56:13.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:56:13.656+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:56:13.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:56:13.826+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:56:13.764+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:56:13.837+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:56:14.024+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.486 seconds
[2024-10-27T14:56:58.496+0000] {processor.py:186} INFO - Started process (PID=702) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:56:58.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:56:58.569+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:56:58.568+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:56:58.627+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:56:58.620+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:56:58.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:56:58.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.236 seconds
[2024-10-27T14:57:29.129+0000] {processor.py:186} INFO - Started process (PID=763) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:57:29.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:57:29.138+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:57:29.137+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:57:29.170+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:57:29.162+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:57:29.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:57:29.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.107 seconds
[2024-10-27T14:57:59.428+0000] {processor.py:186} INFO - Started process (PID=825) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:57:59.429+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:57:59.432+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:57:59.431+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:57:59.457+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:57:59.448+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:57:59.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:57:59.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.078 seconds
[2024-10-27T14:58:29.917+0000] {processor.py:186} INFO - Started process (PID=889) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:58:29.919+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:58:29.924+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:58:29.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:58:29.953+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:58:29.946+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:58:29.956+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:58:30.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.098 seconds
[2024-10-27T14:59:00.588+0000] {processor.py:186} INFO - Started process (PID=952) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:59:00.605+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T14:59:00.626+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:59:00.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:59:00.692+0000] {logging_mixin.py:190} INFO - [2024-10-27T14:59:00.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 9, in <module>
    from crawl_data.crawl_data_flow import scrape_data_core_flow
ModuleNotFoundError: No module named 'crawl_data'
[2024-10-27T14:59:00.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T14:59:00.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.299 seconds
[2024-10-27T15:05:54.869+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:05:54.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:05:54.919+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:05:54.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:05:55.904+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:05:55.865+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:05:55.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:05:56.690+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 2.021 seconds
[2024-10-27T15:06:59.288+0000] {processor.py:186} INFO - Started process (PID=153) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:06:59.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:06:59.336+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:06:59.335+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:06:59.669+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:06:59.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:06:59.687+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:06:59.796+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.565 seconds
[2024-10-27T15:07:33.515+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:07:33.522+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:07:33.546+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:07:33.542+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:07:33.775+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:07:33.765+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:07:33.779+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:07:33.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.573 seconds
[2024-10-27T15:08:11.795+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:08:11.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:08:11.853+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:08:11.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:08:12.259+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:08:12.220+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:08:12.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:08:12.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.611 seconds
[2024-10-27T15:09:04.439+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:09:04.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:09:04.482+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:09:04.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:09:05.051+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:09:04.925+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:09:05.072+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:09:05.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.926 seconds
[2024-10-27T15:09:35.681+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:09:35.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:09:35.692+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:09:35.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:09:35.931+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:09:35.913+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:09:35.937+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:09:35.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.312 seconds
[2024-10-27T15:10:08.845+0000] {processor.py:186} INFO - Started process (PID=446) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:10:08.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:10:08.869+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:10:08.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:10:09.068+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:10:09.047+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:10:09.076+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:10:09.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.316 seconds
[2024-10-27T15:10:40.377+0000] {processor.py:186} INFO - Started process (PID=507) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:10:40.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:10:40.392+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:10:40.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:10:40.594+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:10:40.580+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:10:40.602+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:10:40.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.293 seconds
[2024-10-27T15:11:13.389+0000] {processor.py:186} INFO - Started process (PID=570) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:11:13.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:11:13.411+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:11:13.410+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:11:13.699+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:11:13.676+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:11:13.707+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:11:13.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.422 seconds
[2024-10-27T15:11:44.620+0000] {processor.py:186} INFO - Started process (PID=632) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:11:44.642+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:11:44.680+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:11:44.677+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:11:45.642+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:11:45.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:11:45.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:11:45.971+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 1.431 seconds
[2024-10-27T15:12:43.133+0000] {processor.py:186} INFO - Started process (PID=656) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:12:43.192+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:12:43.449+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:12:43.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:12:51.307+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:12:49.699+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:12:51.667+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:12:53.888+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 11.793 seconds
[2024-10-27T15:17:44.575+0000] {processor.py:186} INFO - Started process (PID=760) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:17:44.633+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:17:44.716+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:17:44.706+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:17:47.885+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:17:47.613+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:17:47.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:17:49.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 5.205 seconds
[2024-10-27T15:23:41.192+0000] {processor.py:186} INFO - Started process (PID=868) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:23:41.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:23:41.447+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:23:41.443+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:23:45.158+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:23:44.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:23:45.179+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:23:47.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 9.702 seconds
[2024-10-27T15:29:03.925+0000] {processor.py:186} INFO - Started process (PID=982) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:29:03.938+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:29:03.949+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:29:03.949+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:29:04.620+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:29:04.539+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:29:04.626+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:29:04.827+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 0.966 seconds
[2024-10-27T15:29:46.615+0000] {processor.py:186} INFO - Started process (PID=1030) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:29:46.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T15:29:46.687+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:29:46.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:29:47.348+0000] {logging_mixin.py:190} INFO - [2024-10-27T15:29:47.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_ingestion.pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_ingestion.pipeline.py", line 11, in <module>
    from dags.transform import transform
  File "/opt/airflow/dags/transform.py", line 1, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-10-27T15:29:47.376+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T15:29:49.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 3.094 seconds
[2024-10-27T16:08:24.627+0000] {processor.py:186} INFO - Started process (PID=458) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T16:08:24.754+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T16:08:25.029+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:08:25.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T16:08:45.343+0000] {processor.py:925} INFO - DAG(s) 'spotify_data_ingestion_pipeline' retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T16:08:50.136+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:08:50.129+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:spotify_data_ingestion_pipeline
[2024-10-27T16:08:50.260+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:08:50.260+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:spotify_data_ingestion_pipeline
[2024-10-27T16:08:50.292+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:08:50.291+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:spotify_data_ingestion_pipeline
[2024-10-27T16:08:50.322+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:08:50.322+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:spotify_data_ingestion_pipeline
[2024-10-27T16:08:50.345+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:08:50.344+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:spotify_data_ingestion_pipeline
[2024-10-27T16:08:50.393+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:08:50.392+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:spotify_data_ingestion_pipeline
[2024-10-27T16:08:50.460+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:08:50.459+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:spotify_data_ingestion_pipeline
[2024-10-27T16:08:50.489+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:08:50.462+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-27T16:08:50.786+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:08:50.776+0000] {dag.py:3262} INFO - Creating ORM DAG for spotify_data_ingestion_pipeline
[2024-10-27T16:08:50.907+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:08:50.906+0000] {dag.py:4180} INFO - Setting next_dagrun for spotify_data_ingestion_pipeline to 2024-10-26 00:00:00+00:00, run_after=2024-10-27 00:00:00+00:00
[2024-10-27T16:08:51.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 27.748 seconds
[2024-10-27T16:11:04.723+0000] {processor.py:186} INFO - Started process (PID=539) to work on /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T16:11:04.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_ingestion.pipeline.py for tasks to queue
[2024-10-27T16:11:04.812+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:11:04.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T16:11:16.084+0000] {processor.py:925} INFO - DAG(s) 'spotify_data_ingestion_pipeline' retrieved from /opt/airflow/dags/data_ingestion.pipeline.py
[2024-10-27T16:11:17.436+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:11:17.435+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-10-27T16:11:19.512+0000] {logging_mixin.py:190} INFO - [2024-10-27T16:11:19.511+0000] {dag.py:4180} INFO - Setting next_dagrun for spotify_data_ingestion_pipeline to 2024-10-26 00:00:00+00:00, run_after=2024-10-27 00:00:00+00:00
[2024-10-27T16:11:20.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_ingestion.pipeline.py took 15.924 seconds
